{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0e68f002",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Z-transform of x[n] = a^n u[n]:\n",
      "⎧     1            │a│    \n",
      "⎪  ───────     for │─│ < 1\n",
      "⎪    a             │z│    \n",
      "⎪  - ─ + 1                \n",
      "⎪    z                    \n",
      "⎪                         \n",
      "⎪  ∞                      \n",
      "⎨ ___                     \n",
      "⎪ ╲                       \n",
      "⎪  ╲    n  -n             \n",
      "⎪  ╱   a ⋅z     otherwise \n",
      "⎪ ╱                       \n",
      "⎪ ‾‾‾                     \n",
      "⎪n = 0                    \n",
      "⎩                         \n",
      "Z-transform of x[n] = a^n u[n]:\n",
      "⎧     1             1       \n",
      "⎪   ─────      for ─── < 1/2\n",
      "⎪       2          │z│      \n",
      "⎪   1 - ─                   \n",
      "⎪       z                   \n",
      "⎪                           \n",
      "⎪  ∞                        \n",
      "⎨ ___                       \n",
      "⎪ ╲                         \n",
      "⎪  ╲    n  -n               \n",
      "⎪  ╱   2 ⋅z      otherwise  \n",
      "⎪ ╱                         \n",
      "⎪ ‾‾‾                       \n",
      "⎪n = 0                      \n",
      "⎩                           \n",
      "Z-transform of the unit step signal u[n]:\n",
      "⎧    1           1     \n",
      "⎪  ─────    for ─── < 1\n",
      "⎪      1        │z│    \n",
      "⎪  1 - ─               \n",
      "⎪      z               \n",
      "⎪                      \n",
      "⎪  ∞                   \n",
      "⎨ ___                  \n",
      "⎪ ╲                    \n",
      "⎪  ╲    -n             \n",
      "⎪  ╱   z     otherwise \n",
      "⎪ ╱                    \n",
      "⎪ ‾‾‾                  \n",
      "⎪n = 0                 \n",
      "⎩                      \n",
      "Z-transform of x[n] = exp(alpha * n) u[n]:\n",
      "  ∞           \n",
      " ___          \n",
      " ╲            \n",
      "  ╲    -n  α⋅n\n",
      "  ╱   z  ⋅ℯ   \n",
      " ╱            \n",
      " ‾‾‾          \n",
      "n = 0         \n",
      "Z-transform of the finite sequence {1, 2, 3}:\n",
      "Z-transform of x[n] = sin(omega * n) u[n]:\n",
      "  ∞               \n",
      " ___              \n",
      " ╲                \n",
      "  ╲    -n         \n",
      "  ╱   z  ⋅sin(n⋅ω)\n",
      " ╱                \n",
      " ‾‾‾              \n",
      "n = 0             \n"
     ]
    }
   ],
   "source": [
    "import sympy as sp\n",
    "# Define symbols\n",
    "n, z, a = sp.symbols('n z a')\n",
    "# Define the signal x[n] = a^n * u[n]\n",
    "x_n = a**n\n",
    "# Compute the Z-transform\n",
    "X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))\n",
    "# Print the result\n",
    "print(\"Z-transform of x[n] = a^n u[n]:\")\n",
    "sp.pprint(X_z, use_unicode=True)\n",
    "\n",
    "# Define symbols\n",
    "n, z, a = sp.symbols('n z a')\n",
    "# Define the signal x[n] = a^n * u[n]\n",
    "x_n = 2**n\n",
    "# Compute the Z-transform\n",
    "X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))\n",
    "# Print the result\n",
    "print(\"Z-transform of x[n] = a^n u[n]:\")\n",
    "sp.pprint(X_z, use_unicode=True)\n",
    "\n",
    "import sympy as sp\n",
    "# Define symbols\n",
    "n, z = sp.symbols('n z')\n",
    "# Define the unit step signal u[n]\n",
    "u_n = 1\n",
    "# Compute the Z-transform\n",
    "U_z = sp.summation(u_n * z**(-n), (n, 0, sp.oo))\n",
    "# Print the result\n",
    "print(\"Z-transform of the unit step signal u[n]:\")\n",
    "sp.pprint(U_z, use_unicode=True)\n",
    "import sympy as sp\n",
    "# Define symbols\n",
    "n, z, alpha = sp.symbols('n z alpha')\n",
    "# Define the signal x[n] = exp(alpha * n) * u[n]\n",
    "x_n = sp.exp(alpha * n)\n",
    "# Compute the Z-transform\n",
    "X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))\n",
    "# Print the result\n",
    "print(\"Z-transform of x[n] = exp(alpha * n) u[n]:\")\n",
    "sp.pprint(X_z, use_unicode=True)\n",
    "\n",
    "import sympy as sp\n",
    "# Define symbols\n",
    "n, z = sp.symbols('n z')\n",
    "# Define the finite sequence x[n] = {1, 2, 3}\n",
    "x_n = [1, 2, 3]\n",
    "# Compute the Z-transform manually\n",
    "X_z = sum(x_n[i] * z**(-i) for i in range(len(x_n)))\n",
    "# Print the result\n",
    "print(\"Z-transform of the finite sequence {1, 2, 3}:\")\n",
    "\n",
    "import sympy as sp\n",
    "# Define symbols\n",
    "n, z, omega = sp.symbols('n z omega')\n",
    "# Define the sinusoidal sequence x[n] = sin(omega * n) * u[n]\n",
    "x_n = sp.sin(omega * n)\n",
    "# Compute the Z-transform\n",
    "X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))\n",
    "# Print the result\n",
    "print(\"Z-transform of x[n] = sin(omega * n) u[n]:\")\n",
    "sp.pprint(X_z, use_unicode=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3f879a5",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'serial'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)\n",
      "Cell \u001b[1;32mIn[2], line 1\u001b[0m\n",
      "\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mserial\u001b[39;00m\n",
      "\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtime\u001b[39;00m\n",
      "\u001b[0;32m      3\u001b[0m \u001b[38;5;66;03m# Initialize Serial Communication (Replace 'COM3' with the correct port)\u001b[39;00m\n",
      "\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'serial'"
     ]
    }
   ],
   "source": [
    "import serial\n",
    "import time\n",
    "# Initialize Serial Communication (Replace 'COM3' with the correct port)\n",
    "arduino = serial.Serial(port='COM3', baudrate=9600, timeout=1)\n",
    "time.sleep(2)  # Allow time for Arduino to reset\n",
    "\n",
    "def send_command(command):\n",
    "    arduino.write(command.encode())  # Send command as bytes\n",
    "    print(f\"Sent: {command}\")\n",
    "\n",
    "while True:\n",
    "    user_input = input(\"Enter '1' to turn ON LED, '0' to turn OFF, 'q' to quit: \")\n",
    "    if user_input in ['1', '0']:\n",
    "        send_command(user_input)\n",
    "    elif user_input == 'q':\n",
    "        print(\"Exiting...\")\n",
    "        break\n",
    "    else:\n",
    "        print(\"Invalid input! Enter '1', '0', or 'q'.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
